### ISSUE TITLE
ID가 10개 이상일 시 Internal Server Error

### ISSUE THREAD

**Issue by 1392-github** [1392-github/TheWikiEngine#5]
계정을 10개 이상 만든 후 10번째 이후로 만든 계정에 로그인하면 Internal Server Error가 발생하는 오류가 있습니다
```
[2023-09-24 18:43:04,072] ERROR in app: Exception on /raw/FrontPage [GET]
Traceback (most recent call last):
  File "C:\Users\noname\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\noname\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\noname\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\noname\AppData\Roaming\Python\Python310\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\noname\Downloads\TheWikiEngine\app.py", line 260, in doc_raw
    return rt("document_raw.html", doc_title=doc_title, doc_data=d), code
  File "C:\Users\noname\Downloads\TheWikiEngine\app.py", line 104, in rt
    k['isowner'] = isowner()
  File "C:\Users\noname\Downloads\TheWikiEngine\app.py", line 40, in isowner
    return c.execute('''select exists (
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 2 supplied.
127.0.0.1 - - [24/Sep/2023 18:43:04] "[35m[1mGET /raw/FrontPage?rev=5 HTTP/1.1[0m" 500 -
```
# 원리 설명
The Wiki Engine에서는 계정을 만드면 각각의 고유 숫자 ID를 부여합니다
그런데 계정이 10개 이상이면 이 ID가 2개가 되면서
```
def isowner():
    if 'id' not in session:
        return False
    return c.execute('''select exists (
	select *
	from user
	where id = ?
	and name = (
		select value
		from config
		where name = "owner"
	)
)''', (str(session['id']))).fetchone()[0] == 1
```
에서 오류가 발생합니다
참고로, isowner() 함수는 헤더의 "관리 도구" 버튼을 표시할지 여부를 결정하기 위해서 모든 페이지에서 호출됩니다
v8에서 수정되었습니다
v5~v7에서 발생합니다

**Comment by 1392-github** [comment]
v8

**Comment by 1392-github** [comment]
그나저마 계정 고유 번호 비교하는데 str은 왜 넣은 건지
